name: Build C++ Graphics Engine

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libgl1-mesa-dev libglu1-mesa-dev libglew-dev libglfw3-dev
    
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake glew glfw
    
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake
        # For Windows, we'll use vcpkg to install graphics libraries
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg integrate install
        ./vcpkg install glew:x64-windows glfw3:x64-windows opengl:x64-windows
    
    - name: Configure CMake (Ubuntu/macOS)
      if: matrix.os != 'windows-latest'
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    
    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} .
    
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
    
    - name: Upload artifacts (Ubuntu/macOS)
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: engine-${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          build/engine
          build/res/
    
    - name: Upload artifacts (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: engine-${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          build/${{ matrix.build_type }}/engine.exe
          build/res/
